seeds: [0, 1] # add more later

dataset:
  load: True
  ops: [not, and, or, if_then]
  n_variables: [10, 20]
  n_ops: [8, 256]
  f_path: './data/datasets/'

models:
  mlp:
    sizes: [
      [1024, 2056, 1024, 512, 256],
      [5, 10, 5, 2],
    ]
    activ_functions: [
      'relu'
    ]
  kan:
    width: [1, 5, 1] # 1d input, 1d output, 5 hidden neurons
    grid: 3 # grid intervalls
    k: 3 # cubic spline


train:
  n_epochs: 100
  batch_size: 32
  lr: 0.0005
