seeds: [0, 1, 3, 4, 5] # add more later

dataset:
  ops: [not, and, or, if_then, xor]
  n_variables: [5, 10, 15]
  n_ops: [8, 16, 32, 64]
  f_path: './data/datasets/'

models:
  mlp:
    sizes: [
      [4, 8, 16, 8, 4],
      [32, 64, 128, 64, 32],
      [128, 256, 512, 256, 128],
      [256, 256],
      [64, 64]
    ]
  kan:
    width: [
      [1, 2, 1],
      [1, 5, 1],
      [2, 5, 2],
      [10, 10],
      [5, 10, 10, 5],
    ]
    grid: 3 # grid intervalls
    k: 4 # degree of the spline


train:
  n_epochs: 50
  batch_size: 32
  lr: 0.0005
  log_dir: logs
