seeds: [1, 2, 3, 4] # add more later
# seeds: [0, 1, 3, 4, 5] # add more later

dataset:
  ops: [not, and, or, if_then, xor]
  n_variables: [10, 15]
  n_ops: [32, 64]
  f_path: './data/datasets/'

models:
  mlp:
    sizes: [
      [1, 2, 1],
      [2, 4, 2],
      [1, 5, 1],
      [2, 5, 2],
      [4, 16, 4]
    ]
  kan:
    width: [
      [1, 2, 1],
      [2, 4, 2],
      [1, 5, 1],
      [2, 5, 2],
      [4, 16, 4]
    ]
    grid: 3 # grid intervalls
    k: 4 # degree of the spline


train:
  n_epochs: 40
  batch_size: 32
  lr: 0.0005
  log_dir: logs
