seeds: [0, 1] # add more later

dataset:
  load: True
  ops: [not, and, or, if_then]
  n_variables: [10, 20]
  n_ops: [8, 256]
  f_path: './data/datasets/'

models:
  mlp:
    sizes: [
      [256, 512, 1024, 2048, 1024, 512, 256],
      [64, 128, 128, 64]
    ]
  kan:
    width: [
      [1, 5, 1],
      [5, 10, 5],
    ]
    grid: 3 # grid intervalls
    k: 3 # cubic spline


train:
  n_epochs: 50
  batch_size: 32
  lr: 0.0005
  log_dir: logs
