seeds: [0, 1] # add more later

dataset:
  load: True
  ops: [not, and, or, if_then]
  n_variables: [10, 20]
  n_ops: [8, 256]
  f_path: './data/datasets/'

models:
  mlp:
    sizes: [
      [5, 10, 5, 2],
      [100, 200, 100, 2],
    ]
    activ_functions: [
      'relu',
      'tanh',
      'sigmoid'
    ]
  kan:
    dummy: [dummy]
  
train:
  n_epochs: 10
  batch_size: 32
